### PR TITLE
Requesting access to public-good-instace to help out with Sigstore GA…

### PR DESCRIPTION
**Pull request by rawlingsj**
… project

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

### CODE REVIEW

**Comment by rawlingsj** [comment]
I wasn't sure if this PR should add to the users.yaml which I've done, or instead as a collaborator to the repository similar to this https://github.com/sigstore/community/blob/0edc921ba4153a965924618ab0d010344784f293/github-sync/github-data/repositories.yaml#L821-L822

I can change the PR if it's the latter.

**Comment by haydentherapper** [comment]
This LGTM, we should move everyone out from a collaborator into a team at some point

**Comment by hectorj2f** [comment]
lgtm

**Comment by cpanato** [comment]
> This LGTM, we should move everyone out from a collaborator into a team at some point

i will do that

**Comment by cpanato** [comment]
need tsc approval

@rawlingsj can you please rebase your pr? thanks

**Review by priyawadhwa — APPROVED** [review]

**Comment by rawlingsj** [comment]
> can you please rebase your pr? thanks

sure thing - all done, thanks.

**Comment by cpanato** [comment]
will need another rebase :)

**Comment by rawlingsj** [comment]
> will need another rebase :)

done :)

**Review by cpanato — APPROVED** [review]

**Pull request merged**
