### PR TITLE
Add maintainer for protobuf-specs

### PR DESCRIPTION
**Pull request by haydentherapper**
William has significantly contributed to the Python client library and has been active in discussions and reviews around client specifications and this protobuf library.

Also removed one inactive admin (they're still a maintainer) and cleaned up duplicated maintainer (specified in users.yaml).

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc other maintainers for +1s: @kommendorkapten @znewman01 

cc for approval: @bobcallaway @priyawadhwa @trevrosen

**Comment by haydentherapper** [comment]
(@kommendorkapten fyi you're still a maintainer, just removed from collaborator since you're already in the team with maintainer perms)

**Review by bobcallaway — APPROVED** [review]

**Comment by cpanato** [comment]
@haydentherapper please rebase we did some changes to add another org :)

**Comment by haydentherapper** [comment]
Done

**Review by kommendorkapten — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
