### PR TITLE
Propose adding myself as maintainer of sigstore/sigstore, clean up rekor-monitor-codeowners

### PR DESCRIPTION
**Pull request by haydentherapper**
sigstore/sigstore PRs have been sitting without approvals, so I'd like to propose adding myself as a codeowner to unblock development in this repository. I've made a number of contributions to the repository, including some of the code that has recently been moved into the repo recently (fulcio/TUF).

I also updated rekor-monitor-codeowners for two members (myself and another) to not be able to maintain the team, but still be a member.

Signed-off-by: Hayden B <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
@dlorenc @bobcallaway @lukehinds

**Comment by haydentherapper** [comment]
I looked at https://github.com/sigstore/sigstore/graphs/contributors to see if there were any other candidates with more contributions, but didn't see other active community members.

**Comment by cpanato** [comment]
For TSC approval

@lukehinds @bobcallaway @trevrosen @SantiagoTorres

**Comment by bobcallaway** [comment]
@dekkagaijin as you're a maintainer on s/s as well, so adding you to this for feedback

**Comment by bobcallaway** [comment]
LGTM as well

**Comment by SantiagoTorres** [comment]
+1 LGTM

**Comment by cpanato** [comment]
@haydentherapper can you rebase?

**Comment by haydentherapper** [comment]
@cpanato done

**Comment by cpanato** [comment]
i will take the `lgtm` from the TSC members as a approval for this PR :)

**Review by cpanato — APPROVED** [review]

**Pull request merged**
