### PR TITLE
Propose myself with review permissions for Rekor

### PR DESCRIPTION
**Pull request by haydentherapper**
I am very familiar with the codebase and transparency logs in general, and adding myself as a reviewer should help with getting PRs approved promptly.

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @bobcallaway @priyawadhwa

**Review by bobcallaway — APPROVED** [review]
sgtm!

**Review by cpanato — APPROVED** [review]
+1

**Comment by cpanato** [comment]
but maybe you are added to the rekor-codeowners instead directly in the repo?

**Comment by haydentherapper** [comment]
If maintainers are ok with me being added to codeowners which would give me merging perms rather than just write perms, that’s good with me! I haven’t met the bar for PRs though.

**Comment by cpanato** [comment]
both have same permissions

**Comment by haydentherapper** [comment]
Maintain for codeowners can also merge, push can only approve PRs.

**Comment by cpanato** [comment]
> Maintain for codeowners can also merge, push can only approve PRs.

no, maintain and push permission can both merge prs

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

the mantain can do a bit more, like configure how to merge prs (squash, merge...) along with other configuration things

**Comment by haydentherapper** [comment]
Ah, I think adding the branch protection rules is what limits it. For example, I have this same set up for cosign but can’t merge.

**Comment by cpanato** [comment]
will wait another @sigstore/core-team member to approve this PR then we can merge

**Comment by haydentherapper** [comment]
cc @priyawadhwa

**Comment by haydentherapper** [comment]
cc @lukehinds @trevrosen @SantiagoTorres bumping, since we've got some PRs that need reviews in rekor

**Review by trevrosen — APPROVED** [review]

**Comment by trevrosen** [comment]
:shipit:

**Pull request merged**
