### PR TITLE
Import pulumi code and import sigstore GH data

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
This PR import the Pulumi GitHub sync from https://github.com/cpanato/pulumi-github-sync, setup the pulumi account and import the existing GitHub Sigstore data to Pulumi

We have a Pulumi open source project account

TODO:
- add the CI automation, in progress here: https://github.com/sigstore/community/pull/59
- Add more documentation (will do as follow-up)
- and check the integration with Pulumi, need this PR and #59 to test

/assign @dlorenc @lukehinds @bobcallaway

### CODE REVIEW

**Comment by dlorenc** [comment]
I think the only real thing this is missing is some documentation. At a minimum we should get:

* Instructions on how to operate the infrastructure for the infra team
* Instructions for community members on how to add themselves to the org
* Instructions for community members on how to create and configure a new repo

**Comment by dlorenc** [comment]
If this is a pure import, then I think we should leave it as is rather than review the permissions now. IMO, we should get this merged and operational, then do a pass on the actual permissions and see what we can clean up.

**Comment by cpanato** [comment]
> * community members on how to ad

was planning to do this in a follow-up to reduce the PR size and make it easier to review

**Comment by dlorenc** [comment]
> was planning to do this in a follow-up to reduce the PR size and make it easier to review

Sgtm

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
