### PR TITLE
docs: improves readme

### PR DESCRIPTION
**Pull request by andresgalante**
This PR aims to create a more welcoming README to the Sigstore community. Let me know what you think 😄

I am sorry for the other closed PRs. Now DCO is passing.

### CODE REVIEW

**Review by haydentherapper — CHANGES_REQUESTED** [review]
Sorry if something was unclear from the other PR, but we shouldn’t change the readme here, this is general community guidelines.

**Comment by andresgalante** [comment]
Ok, if the README is ok as is, then let's close this PR.

Should I fix this https://github.com/sigstore/community/blob/main/CONTRIBUTING.md ?

**Comment by haydentherapper** [comment]
All good, I just made some small updates. We can close this PR.

**Comment by andresgalante** [comment]
Excellent, thanks @haydentherapper

**Pull request closed without merging**
