### PR TITLE
remove inactive users

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
follow up of #114

### CODE REVIEW

**Comment by cpanato** [comment]
if approve, i will unlock the deletion, because it is locked to avoid deletion by mistake

```
   stderr: [resource plugin github-4.11.0] installing
  error: Preview failed: unable to delete resource "urn:pulumi:github-prod::sigstore-github-sync::github:index/membership:Membership::A0su"
  as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up` or use the command:
  `pulumi state unprotect 'urn:pulumi:github-prod::sigstore-github-sync::github:index/membership:Membership::A0su'`
  error: Preview failed: unable to delete resource "urn:pulumi:github-prod::sigstore-github-sync::github:index/membership:Membership::efebarlas"
  as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up` or use the command:
  `pulumi state unprotect 'urn:pulumi:github-prod::sigstore-github-sync::github:index/membership:Membership::efebarlas'`
  error: preview failed
```

**Review by haydentherapper — APPROVED** [review]

**Comment by cpanato** [comment]
gently ping @SantiagoTorres :)

**Comment by haydentherapper** [comment]
Ping @SantiagoTorres, to remove inactive members

**Review by SantiagoTorres — APPROVED** [review]

**Comment by cpanato** [comment]
i've rebased and remove the protection need a new approval @SantiagoTorres

**Review by SantiagoTorres — APPROVED** [review]

**Pull request merged**
