### PR TITLE
add branch protection for release-1.13 in cosign repo

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add branch protection for `release-1.13` in cosign repo

### CODE REVIEW

**Review by bobcallaway — COMMENTED** [review]
why is this branch named differently?

**Comment by priyawadhwa** [comment]
@bobcallaway the `1.0-fork` is a fork of the 1.0 code so that we can start merging 2.0 code changes into main! We figured there likely wasn't going to be a 1.x release anytime soon & if there is we can cherry pick commits into that branch for the release.

**Comment by cpanato** [comment]
I think bob means why is called that and not release-1.0

I think we already have a release-1.0 from the past but i can check if i can merge the branch into that then we can use the same naming convention.

What tag the 1.0-fork was based? Then i can try to apply a merge into the release-1.0

**Comment by priyawadhwa** [comment]
> I think bob means why is called that and not release-1.0

Ahhh thanks 😄 

> What tag the 1.0-fork was based?

I just forked it off of the last commit @ HEAD before we started merging in breaking 2.0 changes! (43bde0e2012243fa78363202545e5372b26a29c2)

**Comment by cpanato** [comment]
Ok thanks will try tomorrow

**Comment by cpanato** [comment]
since cosign is on release 1.13 I will create a branch called `release-1.13` to follow the other branches we have and to make it similar to the other projects.

is that ok @bobcallaway @priyawadhwa ?

we most likely to release patches and not new features in that branch, but in case we need to release a 1.14 we create a new branch based on the 1.13

**Comment by priyawadhwa** [comment]
Sounds good, thank you @cpanato !

**Comment by cpanato** [comment]
ok, branch `release-1.13` created based on `43bde0e2012243fa78363202545e5372b26a29c2` commit

**Comment by cpanato** [comment]
PTAL @bobcallaway @priyawadhwa

**Pull request merged**
