### PR TITLE
Updating sig-clients codeowners

### PR DESCRIPTION
**Pull request by haydentherapper**
Updating to the current chairs of sig-clients

### CODE REVIEW

**Comment by haydentherapper** [comment]
FYI @loosebazooka @kommendorkapten Making you maintainers of the sig-clients repos

**Comment by haydentherapper** [comment]
Also @kommendorkapten @loosebazooka you may want to update https://github.com/sigstore/sig-clients/blob/main/README.md#governence with the current chairs

**Review by kommendorkapten — APPROVED** [review]

**Review by bobcallaway — APPROVED** [review]

**Comment by cpanato** [comment]
will be good a rebase, other prs got in

**Comment by haydentherapper** [comment]
rebased @cpanato (and i just found out that since the rebase makes no changes, approvals persist!)

**Comment by loosebazooka** [comment]
> Also @kommendorkapten @loosebazooka you may want to update https://github.com/sigstore/sig-clients/blob/main/README.md#governence with the current chairs

Oh yeah I can do this

**Pull request merged**
