### PR TITLE
DNM: test pulumi update

### PR DESCRIPTION
**Pull request by haydentherapper**

### CODE REVIEW

**Comment by jku** [comment]
To my best understanding these are correct:
* an empty `pushAllowances` list does not mean pushes are not allowed: _Organization administrators, repository administrators, and users with the Maintain role on the repository can always push when all other requirements have passed_   (this means we could clean up repositories.yaml quite a bit by removing maintainers from         pushRestrictions list)
* the pushAllowances list seems to be reasonable for  the projects I checked
* `blocksCreations: true` seems completely reasonable to me: If someone wants to override that, they would have to add support to github-sync though

I'm still baffled by how we only get an added pushAllowances but nothing was removed... What happened to the the `PushRestrictions` used in the previous pulumi version?

**Comment by haydentherapper** [comment]
We could make the change in the conformance org which would only affect one project.

**Comment by jku** [comment]
> * an empty `pushAllowances` list does not mean pushes are not allowed: _Organization administrators, repository administrators, and users with the Maintain role on the repository can always push when all other requirements have passed_   

I keep re-reading this and I'm not sure if it can be true. What does the "restrict who can push" checkbox even mean at this point?

**Comment by jku** [comment]
> We could make the change in the conformance org which would only affect one project.

I think this would be useful. However, I don't have access to the project settings in GitHub UI so I can't compare what it looks right now and what it looks like after applying... Would maybe have to add admin permissions first.


Before that can we figure out this:
* The UI has a checkbox for `Restrict who can push to matching branches` (after checking that you can add users and teams): 
Screenshot from 2024-04-18 16-44-00
* so what is the equivalent of **not checking** that checkbox when using the API?
* or does checking the checkbox in itself do nothing?

**Comment by jku** [comment]
I've got a possible branch in https://github.com/jku/github-sync/tree/tweak-push-restrictions: it tries to avoid setting restrictPushes at all if the list is empty. I assume this is the equivalent of not checking the checkbox at all.

You could modify `github-sync-pr-sigstore.yml` in this PR to do `uses: jku/github-sync@tweak-push-restrictions` instead of sigstore/github-sync@main if you want to test that one...

**Comment by haydentherapper** [comment]
> when the box is not checked, all collaborators can still push to the branch (if other rules do not prevent the push)
> If the the box is checked, only maintainers can push to the branch (if other rules do not prevent the push)

That sounds correct to me, and your fix SGTM. From what I understand, the difference is that those with `push` permissions can both review and merge if the check box is unselected, but only review if the check box is selected (we leverage this in some repos for example to differentiate between reviewers vs codeowners)

**Comment by haydentherapper** [comment]
@jku reran based on merged sync PR

**Comment by haydentherapper** [comment]
Created https://github.com/sigstore/community/pull/434 so that we (we = TSC or anyone who's a maintainer on this repo) can manually run `preview` and `up` to sync.

This SDK bump seems safe, though we'll try in the conformance org first.

**Pull request closed without merging**
