### PR TITLE
import sigstore-js to sigstore org

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
import the `sigstore-js` into pulumi infra and add the config in the yaml

This is just to sync the data, it was applied manually during the import phase.

xref: https://github.com/sigstore/community/pull/81

cc @bdehamer

### CODE REVIEW

**Review by bobcallaway — APPROVED** [review]

**Review by dlorenc — APPROVED** [review]

**Comment by bdehamer** [comment]
@cpanato I can see that the `codeowners-sigstore-js` team was created, but there is no one on it

image

**Comment by cpanato** [comment]
let me check that

**Comment by bdehamer** [comment]
Doh! I see that the entry in the user's file says `sigstore-js-codeowners` not `codeowners-sigstore-js` . . . which was a mistake copied from my original PR 🤦‍♂️

**Comment by cpanato** [comment]
yep, that is, i will fix it

**Pull request merged**
