### PR TITLE
Remove administrative account

### PR DESCRIPTION
**Pull request by haydentherapper**
Chatting with the OpenSSF, this is no longer used for administrative control over a repo, and will instead be managed by joining the OpenSSF GH org.

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc tsc @bobcallaway @trevrosen @lukehinds @SantiagoTorres @priyawadhwa

**Comment by lukehinds** [comment]
Have we done a review on what happens if we join the openssf org permissions wise? Who would get admin rights here, via the association with the openssf org?

**Comment by haydentherapper** [comment]
Just need to unlock the account in pulumi to merge.

**Comment by cpanato** [comment]
Will do that

**Comment by cpanato** [comment]
done

**Comment by bobcallaway** [comment]
lgtm, let me merge as i'm fixing the enterprise org thing as well

**Review by bobcallaway — APPROVED** [review]

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
