### PR TITLE
Added new repository: protobuf-specs

### PR DESCRIPTION
**Pull request by kommendorkapten**
Signed-off-by: Fredrik Skogman <kommendorkapten@github.com>

#### Summary
Adding a new repository `sigstore/protobuf-specs`. 
Closes https://github.com/sigstore/TSC/issues/38

#### Release Note
N/A

#### Documentation
N/A

### CODE REVIEW

**Comment by kommendorkapten** [comment]
This PR is still WIP as I'm not sure if we need to add more people as maintainers and if we need a new team for `pushRestrictions` and `dissimalRestrictions`?

**Comment by haydentherapper** [comment]
Number of maintainers is likely good for now. Following other repos, we could create a "protobuf-specs-team" with maintain privileges, add maintainers as members of that group, and add that team to `pushRestrictions` and `dissimalRestrictions`

**Comment by kommendorkapten** [comment]
It seems the team has to be created before any team assignment can happen, is that correct? If so then I would say the PR is ready, then after the team is created I will create a follow up PR with the team assignment added (they are commented now).

**Comment by bobcallaway** [comment]
https://github.com/orgs/sigstore/teams/protobuf-specs-codeowners now exists

**Comment by kommendorkapten** [comment]
Thanks @bobcallaway, I could not resolve the team to a numerical id, so the team assignment for new repository is not set (for `protobuf-specs-owners`), it's only the core team now that has maintainer permission (and some collaborators).

**Comment by bobcallaway** [comment]
> Thanks @bobcallaway, I could not resolve the team to a numerical id, so the team assignment for new repository is not set (for `protobuf-specs-owners`), it's only the core team now that has maintainer permission (and some collaborators).

Added it (FYI, it is fetchable through https://api.github.com/orgs/sigstore/teams for those who have permission)

**Comment by kommendorkapten** [comment]
I guessed so, but don't have permission :)

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
