### PR TITLE
Remove github sync code and update actions

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Need: https://github.com/sigstore/github-sync/pull/1

As discussed with @bobcallaway we are transferring the github-sync code to it own repository to avoid any possible leak and creating an action to run the changes

 
#### Release Note
n/a

#### Documentation
n/a

### CODE REVIEW

**Review by bobcallaway — APPROVED** [review]

**Comment by bobcallaway** [comment]
@cpanato please merge when ready

**Comment by cpanato** [comment]
> @cpanato please merge when ready

need your review here https://github.com/sigstore/github-sync/pull/1 :)

**Comment by bobcallaway** [comment]
sorry, thought i had done this already. approved!

**Comment by cpanato** [comment]
@bobcallaway I will merge this tomorrow morning and do all the checks, and act if needed

**Pull request merged**
