### PR TITLE
Add triage to cosign & sigstore, update sigstore-triage name

### PR DESCRIPTION
**Pull request by haydentherapper**
The triage team now can triage in Cosign and sigstore/sigstore.

I renamed sigstore-triage to sigstore-go-triage, because it wasn't
clear to me that this team was meant for just the sigstore/sigstore
repo.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @bobcallaway @dlorenc

**Comment by haydentherapper** [comment]
@cpanato Do you know what the test failure is about, a missing access token?

**Comment by cpanato** [comment]
> Details

i will check what is wrong

**Comment by cpanato** [comment]
ahh that is because it is using the `pull_request` and you open a PR from a fork, then the secret will not be injected, we need to change that to the `pull_request_target`

**Comment by cpanato** [comment]
this should fix this pr https://github.com/sigstore/community/pull/70. after we merge you need to rebase this pr

thanks!

**Comment by cpanato** [comment]
closing in favor of https://github.com/sigstore/community/pull/72

**Pull request closed without merging**
