### PR TITLE
New project logos and brand guidelines

### LINKED ISSUE #61: Logo Refresh Stage 2
Following on from the logo refresh work done in #55 this issue tracks the follow up work, which is:
- update the brand guidelines to match the new logo (https://github.com/sigstore/community/blob/main/artwork/Sigstore_Guidelines_2021.pdf)
- update the subproject logos to be more in keeping with the new logo

### LINKED ISSUE #67: Gitsign Logo
This is a distinct issue to track progress towards a logo for the gitsign subproject, though is part of the general sigstore logo refresh stage 2, see #61.

Gitsign should have it's own logo that is distinct but also in keeping with the new Sigstore logo.

### PR DESCRIPTION
**Pull request by tracymiranda**
#### Summary
New project logos and usage guidelines
Closes #61
Closes #67

#### Release Note
* Previous brand guidelines (2021) and subproject logos are deprecated

#### Documentation
NONE

### CODE REVIEW

**Comment by ltagliaferri** [comment]
I wonder if there could be brand guidance for variable backgrounds on the web, since dark mode and light mode can be user set. I [noticed that the logos with transparent backgrounds may not read well](https://github.com/sigstore/.github/issues/18) in both cases and I believe a lot of the usage may be on sites that enable user-selected dark and light mode options. Just having some guidance on whether it's appropriate to use a background, etc. would be helpful 😄

**Comment by tracymiranda** [comment]
@ltagliaferri there is this page in the brand guidelines - is that the sort of guidance you had in mind?
Screen Shot 2022-07-28 at 11 18 52 AM

**Comment by ltagliaferri** [comment]
I saw those, I mean if there is guidance for a singular color scheme that can work on both dark or light mode since webpages for developers are often variable, see the current org screenshot in dark mode:

org page

**Comment by tracymiranda** [comment]
@ltagliaferri I'll check with the designer and take a look how others handle it.

**Comment by tracymiranda** [comment]
@lukehinds @dlorenc @bobcallaway ptal - all the new logo files for merging!

**Review by dlorenc — APPROVED** [review]

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
