### PR TITLE
docs: improves the README

### PR DESCRIPTION
**Pull request by andresgalante**
This PR aims to create a more welcoming README to the Sigstore community.

Let me know what you think 😄

### CODE REVIEW

**Comment by andresgalante** [comment]
I don't know why DCO is failing, the commit is signed 🤔

**Comment by cpanato** [comment]
looks like your git config is not correct

```
Summary
Commit sha: [2956cd9](https://github.com/sigstore/community/pull/327/commits/2956cd9ae44672fdf1b91386788c1c1034e6219f), Author: Andres, Committer: Andres; andres@192.168.0.101 is not a valid email address.
```

**Comment by andresgalante** [comment]
@cpanato yeah, I see that on the DCO message, but if you check, the commit message has a valid email address now as shown here:

https://github.com/sigstore/community/pull/327/commits/2956cd9ae44672fdf1b91386788c1c1034e6219f

I'll try closing this PR and reopening a new one

**Comment by andresgalante** [comment]
@cpanato I had to open a new PR from a  fresh branch, here it is #330

**Pull request closed without merging**
