### PR TITLE
Add repos for initial SIGs

### PR DESCRIPTION
**Pull request by trevrosen**
Signed-off-by: Trevor Rosen <trevrosen@github.com>

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
for the new two repositories can you add, please:

```
    template:
      owner: sigstore
      repository: sigstore-project-template
```

also can you rebase, i see some commits from my previous PR :)

**Comment by cpanato** [comment]
and also sign the DCO 😇

**Comment by trevrosen** [comment]
> and also sign the DCO 😇

Hrrm not sure how that happened, but should be fixed now!

**Review by cpanato — APPROVED** [review]
cool
thanks!

**Pull request merged**
