### PR TITLE
Updating TUF root repo codeowners

### PR DESCRIPTION
**Pull request by haydentherapper**
#### Summary

Adding one of the Sigstore TUF maintainers, and removing another who is not active on the project.

### CODE REVIEW

**Comment by haydentherapper** [comment]
FYI @jku

**Review by cpanato — APPROVED** [review]

**Review by jku — APPROVED** [review]

**Comment by haydentherapper** [comment]
Cc @bobcallaway for merge 

cc @kommendorkapten for +1 to add a maintainer to root signing

**Review by bobcallaway — APPROVED** [review]

**Review by kommendorkapten — APPROVED** [review]

**Comment by cpanato** [comment]
@bobcallaway @haydentherapper getting this error when applying

```
 err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v5 --color auto --exec-kind auto.local --stack sigstore/github-prod --non-interactive
  [resource plugin github-5.26.0] installing
  error: PUT https://api.github.com/repos/sigstore/root-signing-staging/collaborators/sigstore-bot: 422 Role `write-with-bypass` is not available for the sigstore/root-signing-staging repository. []
  error: update failed
  Updating (sigstore/github-prod)
  View Live: https://app.pulumi.com/sigstore/sigstore-github-sync/github-prod/updates/632
```

**Comment by jku** [comment]
this is from #395 -- I must have made a mistake there.

I'll open an issue and do a partial revert if I don't see a solution

**Pull request merged**
