### PR TITLE
Get admin for timestamp-authority and rekor-monitor to set up Scorecard

### PR DESCRIPTION
**Pull request by haydentherapper**
This is needed for setting secrets

Signed-off-by: Hayden B <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @priyawadhwa @bobcallaway

**Comment by haydentherapper** [comment]
cc @cpanato - Based on this output, it looks like the previous PR didn't sync

**Comment by cpanato** [comment]
will fix that as we discussed in slack

we need to manually import the transferred repo before

**Review by priyawadhwa — APPROVED** [review]

**Comment by priyawadhwa** [comment]
will hold on merging as i'm not sure if the repo has been manually transferred yet

**Comment by haydentherapper** [comment]
Thanks Priya! @cpanato Lemme know if I can help with anything

**Comment by cpanato** [comment]
fixed, we had a new repository that was transferred and not created by the automation, so we need to manually import that.
already did and now it is green :)

**Review by cpanato — APPROVED** [review]

**Comment by haydentherapper** [comment]
Thank you!!

**Pull request merged**
