### PR TITLE
set admin permission to some codeowners teams to be able to configure branch protection and status check

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- set admin permission to some codeowners teams to be able to configure branch protection and status check

some codeowners teams have admin permissions already, this PR set other codeowners teams the same permission.

### CODE REVIEW

**Comment by bobcallaway** [comment]
I don't think we want to give maintainers `admin`, which includes the ability to delete a repo. Can we rely on scorecards or allstar to just detect when branch protection is disabled, and file an issue?

**Review by bobcallaway — CHANGES_REQUESTED** [review]
see comment

**Comment by haydentherapper** [comment]
Do you think we can revert the removal of branch protection in https://github.com/sigstore/community/pull/203, until we have another approach? I agree that giving `admin` to all maintainers grants too much.

**Comment by cpanato** [comment]
Should we drop the admin as well for other teams that is already in place?


I will revert the changes @haydentherapper

**Comment by haydentherapper** [comment]
Thanks Carlos! 
I think yes, no one should need admin except for break glass (TSC), repo management should always be done through Pulumi in this repo.

**Pull request closed without merging**
