### PR TITLE
add flxw to the org and to helm charts repo

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add flxw to the org and to helm charts repo
@flxw will help in the helm chart repo

sponsor: 
 - @sabre1041

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Review by sabre1041 — DISMISSED** [review]
LGTM

So excited to have @flxw officially part of the org and building out the Helm ecosystem!

**Comment by bobcallaway** [comment]
I think it's great to add more folks to the helm effort within sigstore, but this change appears to increase permissions from nothing 
 straight to [admin](https://github.com/sigstore/community/blob/b0387b8f27daad3fb635552b5854b1197d36a4b4/github-sync/github-data/repositories.yaml#L688). Is there more context here (in light of our [maintainer ladder](https://github.com/sigstore/community/blob/main/MEMBERSHIP.md)) that I'm missing, or should we be fixing the permissions on the helm group first?

**Comment by cpanato** [comment]
oh! i can fix that permission, that should be just a `write` permission and not `admin`

**Comment by cpanato** [comment]
@bobcallaway done the change and Felix did several contributions to the repo and will be a good addition to help us

**Review by bobcallaway — APPROVED** [review]

**Comment by bobcallaway** [comment]
@sigstore/core-team please weigh in, will merge via lazy-consensus in 5 days unless there is discussion to the contrary

**Review by priyawadhwa — APPROVED** [review]

**Pull request merged**
